### ISSUE TITLE
Change previewer index source to S3 bucket

### ISSUE THREAD

**Issue by oyiptong** [rlr/webtiles-previewer-redux#1]
Change index source from the CDN endpoint to S3 to avoid any stale cache issues.

Here's the S3 bucket for the desktop index JSON: https://tiles-resources-prod-tiless3-qbv71djahz3b.s3.amazonaws.com/desktop_tile_index_v3.json

**Comment by rlr** [comment]
That worked. Thanks!

47c6de35edc5a028f538bacf7c2f23d56ea1d0d7
